### PR TITLE
created slider for login page

### PR DESCRIPTION
**Pull request by atulghate**

### CODE REVIEW

**Review by sharayu0 — CHANGES_REQUESTED** [review]
drush configuration need to export before push

**Review by VighneshSadagopal — APPROVED** [review]

**Comment by guptahemant** [comment]
@atulghate is this PR still applicable?

**Review by sharayu0 — APPROVED** [review]

**Comment by atulghate** [comment]
> @atulghate is this PR still applicable?

yes

**Comment by guptahemant** [comment]
> > @atulghate is this PR still applicable?
> 
> yes

Please resolve conflicts, update PR and ask your peers to review and merge it.

**Pull request closed without merging**
